### ISSUE TITLE
Does not work on Ubuntu 19.10

### ISSUE THREAD

**Issue by olofwalker** [diddlesnaps/gog-galaxy-wine#20] opened 2020-01-03 19:07 UTC
Hi, 

I installed GOG Galaxy on my Ubuntu 19.10 laptop and it just produces a black screen (see image).

I'm using X11 and the NVidia 435 driver on a Thinkpad P50.

![gog_not_working](https://user-images.githubusercontent.com/23613882/71743376-b23a6480-2e64-11ea-9880-f60e7f22a70f.png)

![nvidia_driver](https://user-images.githubusercontent.com/23613882/71743383-b8c8dc00-2e64-11ea-9f59-0605b01b4d91.png)

I also installed GOG Galaxy this way on my other computer, an AMD Threadripper with a AMD graphics card (a Radeon 560), with the same result.

**Comment by leso-kn** [comment] 2020-02-05 16:02
Hi! Maybe try to start the launcher via a terminal and upload a log: `gog-galaxy-wine > launcher-log.txt`

---

I'm on Ubuntu 19.10 too, for me the launcher does not display a black screen.

It opens and behaves as expected (except i'm currently experiencing some issues with a game that will crash right after launching it. This is the only game in my library so not sure if other games are affected but i guess the crash is not related to the launcher).

In terms of gaming, I'm on a very low end setup (Intel NUC):

- Ubuntu 19.10 64bit
- Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 16GB RAM
- X11 (Unity 7 session)

**Comment by leso-kn** [comment] 2020-02-05 16:03
Also, this might be a duplicate of #10

**Comment by novembrea** [comment] 2020-03-26 17:28
```
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
2020-03-26 19:27:01.226 [Information][ (0)] [TID 304][client_renderer]: Log started. Application version: 1.2.66.64 (2020-01-23 13:01).
2020-03-26 19:27:01.229 [Information][ (0)] [TID 304][client_renderer]: Operating system: Windows 7 6.1 (Build 7601: Service Pack 1) (IA32)
2020-03-26 19:27:01.232 [Information][ (0)] [TID 304][client_renderer]: Continuing logging after switching log files from 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log' to log to 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper-Gpu.log'.
2020-03-26 19:27:01.236 [Information][ (0)] [TID 304][client_renderer]: Process with pid 303 identified as Gpu starting to log to own file.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 151 (GLX)
  Request Minor code 6 ()
  Error Serial #185
  Current Serial #184
```
Same issue on 18.04

**Comment by zenmindai** [comment] 2020-04-02 04:09
Same error output on on 19.10. I'm using the same proprietary tested NVIDIA drivers.

> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> 2020-04-01 21:05:01.226 [Information][ (0)] [TID 339][client_renderer]: Log started. Application version: 1.2.66.64 (2020-01-23 13:01).
> 2020-04-01 21:05:01.228 [Information][ (0)] [TID 339][client_renderer]: Operating system: Windows 7 6.1 (Build 7601: Service Pack 1) (IA32)
> 2020-04-01 21:05:01.230 [Information][ (0)] [TID 339][client_renderer]: Continuing logging after switching log files from 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log' to log to 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper-Gpu.log'.
> 2020-04-01 21:05:01.233 [Information][ (0)] [TID 339][client_renderer]: Process with pid 338 identified as Gpu starting to log to own file.
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> X Error:  GLXBadContext
>   Request Major code 151 (GLX)
>   Request Minor code 6 ()
>   Error Serial #185
>   Current Serial #184
> 


> ```
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
> 2020-03-26 19:27:01.226 [Information][ (0)] [TID 304][client_renderer]: Log started. Application version: 1.2.66.64 (2020-01-23 13:01).
> 2020-03-26 19:27:01.229 [Information][ (0)] [TID 304][client_renderer]: Operating system: Windows 7 6.1 (Build 7601: Service Pack 1) (IA32)
> 2020-03-26 19:27:01.232 [Information][ (0)] [TID 304][client_renderer]: Continuing logging after switching log files from 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log' to log to 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper-Gpu.log'.
> 2020-03-26 19:27:01.236 [Information][ (0)] [TID 304][client_renderer]: Process with pid 303 identified as Gpu starting to log to own file.
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> X Error:  GLXBadContext
>   Request Major code 151 (GLX)
>   Request Minor code 6 ()
>   Error Serial #185
>   Current Serial #184
> ```
> 
> Same issue on 18.04

**Comment by gbombadil** [comment] 2020-05-15 22:45
Hello, same error here... 

GTX 1070 (nvidia-driver-440) ubuntu 20.04

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 151 (GLX)
  Request Minor code 6 ()
  Error Serial #185
  Current Serial #184

Regards!

**Comment by DoodleCup** [comment] 2020-06-27 20:35
Same here. Fresh nvidia drivers 440
Zorin OS 15.2 (Ubuntu 18.04 based):

> libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 151 (GLX)
  Request Minor code 6 ()
  Error Serial #185
  Current Serial #184
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
2020-06-27 22:34:24.545 [Information][ (0)] [TID 308][client_renderer]: Log started. Application version: 1.2.66.64 (2020-01-23 13:01).
2020-06-27 22:34:24.550 [Information][ (0)] [TID 308][client_renderer]: Operating system: Windows 7 6.1 (Build 7601: Service Pack 1) (IA32)
2020-06-27 22:34:24.559 [Information][ (0)] [TID 308][client_renderer]: Continuing logging after switching log files from 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log' to log to 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper-Gpu.log'.
2020-06-27 22:34:24.567 [Information][ (0)] [TID 308][client_renderer]: Process with pid 307 identified as Gpu starting to log to own file.

**Comment by tonywang531** [comment] 2020-07-28 09:58
GTX 1070 (nvidia-driver-440) ubuntu 20.04
Mine does not show anything on the screen. It just stuck at prepare windows environment 0% forever.
I have installed canberra-gtk-module using sudo apt install, the issue is still not resolved.
<pre>ln: failed to create symbolic link &apos;./settings.ini&apos;: File exists
ln: failed to create symbolic link &apos;./bookmarks&apos;: File exists
ln: failed to create symbolic link &apos;./gtkfilechooser.ini&apos;: File exists
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">18:54:54.964</font>: Failed to load module &quot;canberra-gtk-module&quot;
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">18:54:54.964</font>: Failed to load module &quot;canberra-gtk-module&quot;
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">18:54:54.965</font>: Failed to load module &quot;canberra-gtk-module&quot;
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">18:54:54.965</font>: Failed to load module &quot;canberra-gtk-module&quot;

(yad:47798): Gtk-<font color="#C4A000"><b>WARNING</b></font> **: <font color="#3465A4">18:54:54.987</font>: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(yad:47796): Gtk-<font color="#C4A000"><b>WARNING</b></font> **: <font color="#3465A4">18:54:54.987</font>: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
</pre>

**Comment by padreputativo** [comment] 2021-07-14 22:09
Those "file exists" are not a problem because those are links to other files that appears when we install and uninstall (it seems do not remove all what it creates in the install)

X Error:  GLXBadContext
  Request Major code 151 (GLX)
  Request Minor code 6 ()
  Error Serial #185
  Current Serial #184
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
2021-07-15 00:07:16.775 [Information][ (0)] [TID 404][client_renderer]: Log started. Application version: 1.2.66.64 (2020-01-23 13:01).
2021-07-15 00:07:16.778 [Information][ (0)] [TID 404][client_renderer]: Operating system: Windows 7 6.1 (Build 7601: Service Pack 1) (IA32)
2021-07-15 00:07:16.780 [Information][ (0)] [TID 404][client_renderer]: Continuing logging after switching log files from 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log' to log to 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper-Gpu.log'.
2021-07-15 00:07:16.784 [Information][ (0)] [TID 404][client_renderer]: Process with pid 417 identified as Gpu starting to log to own file.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 151 (GLX)
  Request Minor code 6 ()
  Error Serial #185
  Current Serial #184
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
Logger Exception: Cannot open file(C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log), code 0
2021-07-15 00:07:17.285 [Information][ (0)] [TID 416][client_renderer]: Log started. Application version: 1.2.66.64 (2020-01-23 13:01).
2021-07-15 00:07:17.289 [Information][ (0)] [TID 416][client_renderer]: Operating system: Windows 7 6.1 (Build 7601: Service Pack 1) (IA32)
2021-07-15 00:07:17.295 [Information][ (0)] [TID 416][client_renderer]: Continuing logging after switching log files from 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper.log' to log to 'C:\ProgramData\GOG.com\Galaxy\logs\ClientHelper-Gpu.log'.
2021-07-15 00:07:17.302 [Information][ (0)] [TID 416][client_renderer]: Process with pid 412 identified as Gpu starting to log to own file.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 151 (GLX)
  Request Minor code 6 ()
  Error Serial #185
  Current Serial #184


I preffer AppImages...

posible solution : https://forum.snapcraft.io/t/nvidia-beta-drivers-completely-break-snaps/12392

**Comment by lucyllewy** [comment] 2021-08-18 19:57
Hi, can you please try the release in `candidate` to see if that helps alleviate the issues?

<details>
<summary>If you already have the snap installed...</summary>

```bash
sudo snap refresh --candidate gog-galaxy-wine
```

</details>

<details>
<summary>If you don't have the snap currently installed...</summary>

```bash
sudo snap install --candidate gog-galaxy-wine
```

</details>

**Comment by DavidSlayback** [comment] 2021-09-11 00:25
Can confirm, using the candidate release seems to have fixed this issue for me

nvidia-driver-470 on Kubuntu 20.04

**Comment by angelo-v** [comment] 2021-09-17 17:17
candidate works for me too :tada: nice work!

**Comment by wkitty42** [comment] 2021-09-17 18:42
i had to completely uninstall my original snap gog-galaxy-wine, clean up the little bit of residual mess, and then reinstall via `snap install --candidate gog-galaxy-wine` to get the latest version of GOG...

now on to figuring out how to have it use my already installed games without duplicating them in other drive space... oh yeah, and how to install steam, epic and ubi launchers so gog galaxy can launch them and their games in the same container... i think this is gonna be ""slightly"" painful...

**Comment by leso-kn** [comment] 2021-09-18 08:46
@diddledani Since the issue seems to be fixed in the latest candidate and `candidate` has been merged into `stable` I'd propose to close this issue

**Comment by leso-kn** [comment] 2022-01-05 22:18
Throwing in a reminder that this issue may be closed. @diddledani

**Comment by lucyllewy** [comment] 2022-01-06 09:20
thanks for the ping :-) I'll close it as suggested.

**Closed as completed by lucyllewy** 2022-01-06 09:20 UTC
